"use server";
import {z} from "zod";
import {revalidatePath} from "next/cache";
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin";
const schema=z.object({name:z.string().trim().min(2).max(120),description:z.string().trim().max(1000).optional(),duration:z.coerce.number().int().min(30).max(480),price:z.coerce.number().min(0).max(1000000),participants:z.coerce.number().int().min(1).max(100)});
async function ownCoach(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return null;const admin=createAdminClient();const{data:coach}=await admin.from("coach_profiles").select("id").eq("profile_id",user.id).maybeSingle();return coach?{admin,coach}:null;}
export async function saveCoachService(id:string|null,form:FormData){const parsed=schema.safeParse({name:form.get("name"),description:form.get("description")||undefined,duration:form.get("duration"),price:form.get("price"),participants:form.get("participants")});if(!parsed.success)return{error:parsed.error.issues[0]?.message??"ข้อมูลไม่ถูกต้อง"};const own=await ownCoach();if(!own)return{error:"ไม่พบโปรไฟล์โค้ช"};const values={name:parsed.data.name,description:parsed.data.description??null,duration_minutes:parsed.data.duration,price:parsed.data.price,max_participants:parsed.data.participants};const result=id&&z.string().uuid().safeParse(id).success?await own.admin.from("coach_services").update(values).eq("id",id).eq("coach_profile_id",own.coach.id):id?{error:{message:"invalid"}}:await own.admin.from("coach_services").insert({...values,coach_profile_id:own.coach.id,is_active:true});if(result.error)return{error:"บันทึกแพ็กเกจไม่สำเร็จ"};revalidatePath("/me/coach/services");revalidatePath("/coaches/[id]","page");return{success:true};}
export async function setCoachServiceActive(id:string,active:boolean){if(!z.string().uuid().safeParse(id).success)return{error:"รหัสแพ็กเกจไม่ถูกต้อง"};const own=await ownCoach();if(!own)return{error:"ไม่พบโปรไฟล์โค้ช"};const{error}=await own.admin.from("coach_services").update({is_active:active}).eq("id",id).eq("coach_profile_id",own.coach.id);if(error)return{error:"เปลี่ยนสถานะแพ็กเกจไม่สำเร็จ"};revalidatePath("/me/coach/services");revalidatePath("/coaches/[id]","page");return{success:true};}
